version: "3.6"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      # - ./mongo/SampleCollections:/usr/local/sampleCollections
      - mongo-db:/data/db
    # working_dir: /usr/local/sampleCollections

  server:
    build: ./backend
    volumes:
      - ./backend:/usr/local/server
    working_dir: /usr/local/server
    ports:
      - "9000:9000"
    command: npm start
    depends_on:
      - mongo
      - db

  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    command: npm run start
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
volumes:
  mongo-db: {}
  db-data: {}
